### ISSUE TITLE
Add standard logging of config values

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/pathogen-repo-guide#18]
### Context
With many layers of Snakemake configs provided via default configs and/or CLI options (`--configfile`/`--config`), it is helpful to have a standard way of logging the config values used for a workflow run.

Consensus in discussions below is to go with option 5 of the possible solutions, which has been implemented by @victorlin in WNV with discussion in https://github.com/nextstrain/WNV/commit/d4831ac7c6499bbebdd1e3f919f6a45b68ad1d21. 

<details>

<summary> Previously listed possible solutions </summary>

1. This is done in the ncov workflow with a [`dump_config` rule](https://github.com/nextstrain/ncov/blob/a29a3b2d98b0835444a88c819925fae07ac9b826/Snakefile#L156-L159). Users must specify the target with the same configs as their workflow run to see the config output. 

2. We could print out the config with each workflow run using the `onstart` handler. However, [Snakemake docs](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#onstart-onsuccess-and-onerror-handlers) note that these handlers are _not_ triggered during dry-runs.
     
    ```python
    onstart:
        import yaml, sys
        yaml.dump(config, sys.stdout, explicit_start = True, explicit_end = True)
    ```
  
3. We could print out the config with each workflow run using Snakemake's logger:

    ```python
    import yaml
    from snakemake.logging import logger
    
    # Use default configuration values. Override with Snakemake's --configfile/--config options.
    configfile: "config/defaults.yaml"
    
    logger.info(f"Config is:\n{yaml.dump(config, explicit_start = True, explicit_end = True)}")
    ```
    
4. If the config output is too noisy, we can make it a debug level log that will only output if users provide the `--verbose` flag.
    ```python
    import yaml
    from snakemake.logging import logger
    
    # Use default configuration values. Override with Snakemake's --configfile/--config options.
    configfile: "config/defaults.yaml"
    
    logger.debug(f"Config is:\n{yaml.dump(config, explicit_start = True, explicit_end = True)}")
    ```

5. Always dumping the final, fully-expanded, config-as-loaded to an output file, e.g. `results/config.yaml`. ([comment](https://github.com/nextstrain/pathogen-repo-guide/issues/18#issuecomment-2536821533))

</details>

### TODOs

- [x] https://github.com/nextstrain/shared/pull/61
- [x] https://github.com/nextstrain/pathogen-repo-guide/pull/97
- [ ] Use across pathogen workflows (vendored [GH search](https://github.com/search?q=org%3Anextstrain+write_config+path%3A**vendored**&type=code))
    - [x] [dengue](https://github.com/nextstrain/dengue/blob/9f8799d03251bfa14d32980e9ac24d2758ee87d6/phylogenetic/rules/config.smk#L20)
    - [x] [measles](https://github.com/nextstrain/measles/blob/02d3ad751da28203edba8c12e93cbbf3e1b93227/phylogenetic/rules/config.smk#L18)
    - [x] https://github.com/nextstrain/mpox/pull/370 
    - [x] [mumps](https://github.com/nextstrain/mumps/blob/e2ae02256dd118553ae87b78a43fcf4669899e0a/phylogenetic/rules/config.smk#L28)
    - [x] [rsv](https://github.com/nextstrain/rsv/blob/7e6ccf001ea5adf6507a2a3c169912822e2376df/workflow/snakemake_rules/config.smk#L8) 
    - [x] [WNV](https://github.com/nextstrain/WNV/blob/c6b9b4ef58e7e6c9433adc4609a44d2b0343af0e/phylogenetic/rules/config.smk#L14) 
    - [ ] ...other pathogens TKTK

**Comment by tsibley** [comment]
Option 3 is enticing because it means the actual config in use is always in build logs, so when something unexpectedly goes wrong you can inspect the config (without having to reconstruct it in a separate subsequent run).

**Comment by jameshadfield** [comment]
Option 3 👍

**Comment by tsibley** [comment]
Option 5: Always dumping the final, fully-expanded, config-as-loaded to an output file, e.g. `results/config.yaml`.[¹](https://github.com/nextstrain/measles/pull/55#discussion_r1868332293)

This seems like the best option to me,

- It's written to disk, so not hard to find in all the logging output or lost to scrollback limits.

- It can be directly re-used as input config to reproduce/replicate the config for any given run (rather than having to be snipped out of logs, which can lead to errors).

and @jameshadfield and @joverlee521 +1'd this idea where I originally suggested it.

We could also do option 3 + 5 to get best of both worlds, which could be useful in rare cases when result files are lost (e.g. an out-of-disk-space Batch job), although 3 gets quite lengthy potentially.

**Comment by genehack** [comment]
+1 for option 5, with the "yes, but" addition of "don't call the output `results/config.yaml`, call it something like `results/run_config.yaml` or `results/config_log.yaml`. Consider including a timestamp in the name.

**Comment by jameshadfield** [comment]
[Related thread](https://github.com/nextstrain/measles/pull/55#discussion_r1857418217) where discussion about this is happening in parallel.

**Comment by joverlee521** [comment]
Chatted with @j23414 and @kimandrews on this, they both like the config output file that can easily be re-used for another workflow run.

**Comment by tsibley** [comment]
@genehack 

> don't call the output `results/config.yaml`, call it something like `results/run_config.yaml` or `results/config_log.yaml`.

Why? What makes the addition of `run_` or `_log` important/useful?

(I can guess, but my guesses aren't compelling reasons (in my estimation), so I'm interested in your rationale.)

**Comment by genehack** [comment]
> @genehack
> 
> > don't call the output `results/config.yaml`, call it something like `results/run_config.yaml` or `results/config_log.yaml`.
> 
> Why? What makes the addition of `run_` or `_log` important/useful?

If it's not named `config.yaml`, it can't get confused with `defaults/config.yaml`.

**Comment by victorlin** [comment]
I've implemented option 5 in a draft PR on WNV: https://github.com/nextstrain/WNV/commit/3fa4ac496df2a6f5b2e1b21a59e4f2682559e171

It works well, and will be useful for `augur subsample`.

**Comment by genehack** [comment]
> Potential guardrails:
> 
>     * Use a different file name ([as discussed above](https://github.com/nextstrain/pathogen-repo-guide/issues/18#issuecomment-2546417044))
> 
>     * Add a prominent warning block at the top of the file ([example](https://github.com/nextstrain/WNV/commit/1942d067b63d3d677cf5e06734e10cde131c56b1))
> 
>     * Mark the file as read-only ([example](https://github.com/nextstrain/WNV/commit/110d54d243b951041846d25d80cfaf83c0007d61))

¿Por qué no los tres?

**Comment by victorlin** [comment]
I didn't say we had to pick only one! Also open to more ideas.

**Comment by victorlin** [comment]
My latest thinking is that the shared piece should be a function in `shared/vendored/snakemake/config.smk`. [Drafted](https://github.com/nextstrain/measles/blob/60de29834be1a75fadd20c969501578b3d87cd61/shared/vendored/snakemake/config.smk#L146-L155) in https://github.com/nextstrain/measles/pull/76 along with some other functions.
