### ISSUE TITLE
Standardize GitHub Action workflows for pathogen repos

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/pathogen-repo-guide#25]
Based on discussions below, we are moving forward with separate ingest and phylogenetic GH Action workflows, where the ingest workflow is scheduled to run automatically and the phylogenetic workflow is then triggered by the `workflow_run` event. 

See the zika workflows as examples:
- [ingest](https://github.com/nextstrain/zika/blob/main/.github/workflows/ingest.yaml)
- [phylogenetic](https://github.com/nextstrain/zika/blob/main/.github/workflows/phylogenetic.yaml)

## TODOs

Update existing GH Action workflows to follow the same pattern. Pulled pathogens list from the Nextstrain status page. Purposely excluding avian-flu, ncov, and seasonal-flu since they have different workflow/repo set ups due to historical reasons.

As pathogens workflows are updated, remember to update the listed workflows in [keep-workflows-enabled](https://github.com/nextstrain/.github/blob/master/.github/workflows/keep-workflows-enabled.yaml)

- [x] [ebola](https://github.com/nextstrain/ebola/pull/82)
- [ ] dengue 
- [x] [hmpv](https://github.com/nextstrain/hmpv/pull/11) 
- [ ] lassa 
- [ ] measles 
- [ ] mpox 
- [x] [mumps](https://github.com/nextstrain/mumps/pull/20)  
- [x] [nipah](https://github.com/nextstrain/nipah/pull/11) 
- [x] [oropouche](https://github.com/nextstrain/oropouche/pull/26) 
- [ ] rabies 
- [ ] rsv 
- [x] [seasonal-cov](https://github.com/nextstrain/seasonal-cov/pull/50)
- [ ] WNV 
- [x] [yellow-fever](https://github.com/nextstrain/yellow-fever/pull/36)

---

<details>

<summary> Previous issue content </summary>

## Context 
In a pathogen repo, there will technically be 3 separate workflows that can be run: ingest, phylogenetic, and nextclade. 
It's unclear how we want to set up the standardized GitHub Action workflows for automating them.
This was originally brought up in our [discussion of the the pathogen-repo-template](https://docs.google.com/document/d/1qJ81wyiAo0K3Sr887cOvsfhMc1y__DZ5s-JCZrURuzU/edit). 

### Existing workflows
The existing GitHub Action workflows for automated pathogen repos vary mostly for historical reasons:

1. ncov-ingest/ncov - Initial GISAID data concerns led to separate repos which resulted in separate GH Action workflows. ncov-ingest has daily scheduled GH Action workflows for [GISAID](https://github.com/nextstrain/ncov-ingest/blob/4e90c5ab98b0bb6806f52660386d632812b26dab/.github/workflows/fetch-and-ingest-gisaid-master.yml) and [GenBank](https://github.com/nextstrain/ncov-ingest/blob/4e90c5ab98b0bb6806f52660386d632812b26dab/.github/workflows/fetch-and-ingest-genbank-master.yml). Within the Snakemake workflows, they upload results to S3 and trigger the ncov GH Action workflows for [GISAID](https://github.com/nextstrain/ncov/blob/28fbd6d57985c3a151d237b49fe40eb8216a650c/.github/workflows/rebuild-gisaid.yml) or [open](https://github.com/nextstrain/ncov/blob/28fbd6d57985c3a151d237b49fe40eb8216a650c/.github/workflows/rebuild-open.yml) builds. 
2. mpox - ingest and phylogenetic workflows in the same repo, but kept the same S3 upload and trigger set up for GH Action workflows to mirror ncov. There is only a single [GenBank ingest GH Action workflow](https://github.com/nextstrain/mpox/blob/eccb6c36e11f1d3718924ae4530aaa1b3960b866/.github/workflows/fetch-and-ingest.yaml) scheduled to run daily that triggers three different phylogenetic GH Action workflows with slightly different hard-coded configs ([rebuild-mpxv](https://github.com/nextstrain/mpox/blob/eccb6c36e11f1d3718924ae4530aaa1b3960b866/.github/workflows/rebuild-mpxv.yaml), [rebuild-hmpxv1](https://github.com/nextstrain/mpox/blob/eccb6c36e11f1d3718924ae4530aaa1b3960b866/.github/workflows/rebuild-hmpxv1.yaml), [rebuild-hmpxv1-big](https://github.com/nextstrain/mpox/blob/eccb6c36e11f1d3718924ae4530aaa1b3960b866/.github/workflows/rebuild-hmpxv1-big.yaml)). 
3. rsv - ingest and phylogenetic workflows in the same repo, kept S3 uploads, but does not use triggers. The [ingest GH Action workflow](https://github.com/nextstrain/rsv/blob/0c053250e0f76e368aa3ede84c2d5e38fe32ebb8/.github/workflows/fetch-and-ingest.yaml) is scheduled to run once a week and the [phylogenetic GH Action workflow](https://github.com/nextstrain/rsv/blob/0c053250e0f76e368aa3ede84c2d5e38fe32ebb8/.github/workflows/rebuild.yaml) is scheduled to run 3 hours after the ingest. 

## Open questions

1. Do we run a single action for ingest + phylo? Are these separate jobs, e.g. uploading data to S3 then downloading it for the next job? Or do we have one job which runs all the workflow invocations? Lots of considerations about failures and where they occur to think through here.
2. Coordinating ingest + phylo sounds a lot like a DAG so can we use Snakemake to help here? ([previous discussion on Slack](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1692922949113859))
3. How should ~multiple phylogenetic builds~ phylo builds that require multiple `nextstrain build` invocations be maintained? Do we run these as a matrix within the action (i.e. independent AWS jobs), or do we extend the reusable workflow to accommodate this?

</details>

**Comment by jameshadfield** [comment]
This is a great summary! Thanks @joverlee521

To avoid confusion, I'll use the following definitions as per a [recent slack conversation](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1705009884700299)
* **workflow** refers to the ingest workflow / phylo workflow / nextclade workflow. There is only one per directory, irregardless of the config provided or additional rule sets used.
* **invocation** refers to an invocation of the workflow, e.g. one snakemake command¹. Monkeypox requires 3 invocations of the phylo workflow, each with a different config. 
* **build** refers to an auspice JSON + sidecar files. Most of our repos produce multiple builds. Some phylo workflows require multiple invocations to produce these builds (e.g. mpx), others can use a single invocation to produce multiple builds (e.g. rsv), others use both (ncov). 

---

Thinking about the ideal automated usage of a repo, I'd advocate for the following:

**Ingest** (may require multiple invocations, e.g. ncov)
* Failure would result in no phylo invocations run which are dependent on this data
* Success but no new data would result in no downstream invocations
* Success with new data would proceed

**phylo**
Ideally, failure of any build would not result in unnecessary failure of others. For invocations which use wildcard targets, I _think_ we could achieve this with `--keep-going` + modified upload rules, but I haven't investigated. (This would make reporting on the status a bit more complicated.) For multiple invocations achieving this independence is easier. 

I don't know if I have strong opinions on whether we bundle multiple invocations up into AWS jobs or whether to keep each invocation as it's own separate AWS job, or how to handle the dependency graph, except to say that the simpler the solution the better!


---

¹ This could be made different from an invocation of `nextstrain build` because you can get that to run multiple snakemake invocations in the same AWS job.

**Comment by tsibley** [comment]
I think I generally concur with @jameshadfield's comments above. One minor exception is I'd think to use the term *build* [as we define in our glossary](https://docs.nextstrain.org/page/reference/glossary.html#term-build), where it encompasses everything that goes into and results in an Auspice dataset JSON, not just the JSON itself.

@joverlee521 [wrote](https://github.com/nextstrain/pathogen-repo-template/issues/25#issue-2077914061):

> 2. […] Coordinating ingest + phylo sounds a lot like a DAG so can we use Snakemake to help here?

There's definitely a dependency graph. But ISTM that expressing it in Snakemake only makes sense though if we're running everything in a single giant job (i.e. the answer to questions 1 and 3 is "yes"). If we're _not_ running everything in a single giant job (and I think we shouldn't), then it makes more sense to me to manage this dependency graph in the overarching "orchestration" layer, which for us is GitHub Actions workflows. This would be difficult without the [GitHub job staying attached to the AWS Batch job](https://github.com/nextstrain/.github/pull/54), but we plan to do that anyway!

**Comment by jameshadfield** [comment]
Another thought, prompted from following [the builddir issue](https://github.com/nextstrain/pathogen-repo-template/pull/16):

Many of our pathogens¹ could be run in their entirety (ingest + phylo²) within a single GitHub Actions job (no AWS involved). This would be even simpler if we used a single snakemake workflow² for the entire repo ([e.g.](https://github.com/nextstrain/hepatitisB/)), and could use a single invocation of `pathogen-repo-build` as currently written ([e.g.](https://github.com/nextstrain/hepatitisB/blob/master/.github/workflows/run-builds.yaml)). But that's not a hard requirement, we could also rejig `pathogen-repo-build` to handle multiple workflow invocations with the necessary queuing / conditional execution logic described above. For more complex pathogen repos, even if we used a single Snakefile we would still want to use multiple invocations to deploy separate parts of the snakemake workflow³ to different AWS jobs.

For collaborators, this means any job which fits in a single action job (under 6h, under some memory ceiling) could easily be automated and monitored with only a few minor modifications to `pathogen-repo-build` such as handling nextstrain.org credentials to allow dataset upload to their group, saving the working directory as an artifact etc⁴. 

¹ probably all or most the following: mumps, measles, zika, ebola, rsv, hepB, wnv, dengue. Memory requirements may force some of them to be run on AWS. 

² This would require phylo to not use separate configs to define separate auspice datasets. I.e. how rsv works, not how mpox does it. But I think this is cleaner anyway.

³ Using targets to separate out which parts of the workflow to run in each job

⁴ And if it doesn't run in a single action job we have docs on how they can set up their own AWS environment. 

---

> One minor exception is I'd think to use the term build [as we define in our glossary](https://docs.nextstrain.org/page/reference/glossary.html#term-build), where it encompasses everything that goes into and results in an Auspice dataset JSON, not just the JSON itself.

Thanks -- I've updated my post to use "auspice dataset" to avoid any confusion.

**Comment by tsibley** [comment]
Yeah, agreed that not all pathogens need to run on AWS Batch. ncov-ingest ran on GitHub Actions for the first year before I lifted-and-shifted it to AWS Batch due to disk space.

The memory requirements aren't the only thing to consider: GitHub Actions CPUs are [limited in number](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) (4) and in my experience can be slower than elsewhere. Likely not a deal breaker, but something to consider. Disk space can also be an issue for larger pathogens.

Even without Batch involved, though, GitHub Actions is still our base "orchestration" layer, and it'd be a speed up to hoist top-level fully-independent jobs out of the Snakemake workflow and into parallel GitHub Actions jobs regardless of if they then launch on AWS Batch.

**Comment by tsibley** [comment]
[Some related thoughts](https://github.com/tsibley/blab-standup/blob/master/2024-02-07.md) I jotted down before lunch.

[We'll be using](https://bedfordlab.slack.com/archives/C017E82L6FM/p1707340788078849) our noon (Seattle) slot tomorrow to discuss this topic in general.

**Comment by joverlee521** [comment]
[Notes from our internal discussion](https://docs.google.com/document/d/1moFrcYo_gqQ8AT5tGHTpP0PwG-zMUaRIsERGcccRw-0/edit)

**Comment by joverlee521** [comment]
[Zika's GH Action workflows](https://github.com/nextstrain/zika/tree/fe37759afd63c2ec5772c3094a84a52b877e70e5/.github/workflows) are my latest iteration on the standard GH Action workflows. This was built on @tsibley's [ideas](https://github.com/tsibley/blab-standup/blob/master/2024-02-07.md) and the [discussion](https://docs.google.com/document/d/1moFrcYo_gqQ8AT5tGHTpP0PwG-zMUaRIsERGcccRw-0/edit) we had back in February. 

There are a couple things I'd still like to work through:
- Is there a better method than my [GitHub Action cache workaround](https://github.com/nextstrain/zika/blob/fe37759afd63c2ec5772c3094a84a52b877e70e5/.github/workflows/ingest-to-phylogenetic.yaml#L54) to check if ingest includes new data
- Guarding against [command-line injection in the config override](https://github.com/nextstrain/ncov-ingest/pull/440#discussion_r1571478572)
- Does it make sense to port over `ingest.yaml`, `phylogenetic.yaml`, and `ingest-to-phylogenetic.yaml` as reusable workflows or should they just be workflow templates? My main concern for making them reusable workflows is the variation in pathogen workflow configs, making it hard to standardize the config overrides in [ingest.yaml](https://github.com/nextstrain/zika/blob/fe37759afd63c2ec5772c3094a84a52b877e70e5/.github/workflows/ingest.yaml#L35) and [phylogenetic.yaml](https://github.com/nextstrain/zika/blob/fe37759afd63c2ec5772c3094a84a52b877e70e5/.github/workflows/phylogenetic.yaml#L47)

**Comment by tsibley** [comment]
Instead of having a separate `ingest-to-phylogenetic.yaml` workflow that runs on a schedule and glues the two other workflows together, what about having `ingest.yaml` run on that schedule (`on: schedule: …`) and `phylogenetic.yaml` run after `ingest.yaml` runs ([`on: workflow_run: …`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run)) and is a) successful and b) found new data?

This means the manual and automatic workflows are the same, and we'd avoid issues of drift and additional overhead and multiple sources of workflow run history.

**Comment by joverlee521** [comment]
> Still think we should do what I suggested above…

Yeah, I definitely get this now with the use of the Nextstrain status page to track workflow runs. Although, the newer pathogen repos only have the single ingest-to-phylogenetic.yaml workflow and don't even have the separate ingest/phylogenetic workflows for testing.

**Comment by tsibley** [comment]
Yep. Context [from Slack](https://bedfordlab.slack.com/archives/C0K3GS3J8/p1742575611015739):

> @genehack: How do I force an automated pathogen repo to re-build the phylogenetic workflow without new sequences coming in from the ingest?
>
> @tsibley: Depends on the workflows that are setup. If there's only the "ingest-to-phylogenetic" workflow, then you delete the GitHub Actions cache key and then trigger a "ingest-to-phylogenetic" workflow run. It'll redo all of ingest, though. If you also have separate "ingest" and "phylogenetic" workflows, then you just trigger a "phylogenetic" workflow run.
>
> @tsibley: How to structure these workflows is an [open issue](https://github.com/nextstrain/pathogen-repo-guide/issues/25). Most repos started getting stamped out with at least "ingest-to-phylogenetic" and sometimes also "ingest" and "phylogenetic". I think there's room for improvement.
>
> @genehack: this is for seasonal-cov, which only has ingest-to-phylogenetic, so manual cache invalidation it is!
> thanks.

**Comment by tsibley** [comment]
> Although, the newer pathogen repos only have the single ingest-to-phylogenetic.yaml workflow and don't even have the separate ingest/phylogenetic workflows for testing.

I do think it'd be nice to expose status of ingest/phylo separately on our status page. We could do that by changing what the status page displays or by not putting the two workflows in the same GitHub Actions workflow. I think the latter is better.

**Comment by joverlee521** [comment]
> I do think it'd be nice to expose status of ingest/phylo separately on our status page. We could do that by changing what the status page displays or by not putting the two workflows in the same GitHub Actions workflow. I think the latter is better.

Right, currently on the status page the [mpox](https://status.nextstrain.org/pathogen-workflows.html#mpox) and [rsv](https://status.nextstrain.org/pathogen-workflows.html#rsv) ingest/phylo workflows are separate. Although their GH Action workflow are _not_ set up the way you've suggested, it's nice that it's obvious which workflows failed.

I can work on converting the zika GH Action workflows to the new set up and go from there.

**Comment by genehack** [comment]
> I can work on converting the zika GH Action workflows to the new set up and go from there.

As I said when we were speaking earlier, I'm happy to build on your work on zika to extend this to `yellow-fever` and `seasonal-cov`, to help with documentation, etc.

**Comment by joverlee521** [comment]
> Instead of having a separate `ingest-to-phylogenetic.yaml` workflow that runs on a schedule and glues the two other workflows together, what about having `ingest.yaml` run on that schedule (`on: schedule: …`) and `phylogenetic.yaml` run after `ingest.yaml` runs ([`on: workflow_run: …`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run)) and is a) successful and b) found new data?
> 
> This means the manual and automatic workflows are the same, and we'd avoid issues of drift and additional overhead and multiple sources of workflow run history.

I've implemented this for zika in https://github.com/nextstrain/zika/pull/81.
