### ISSUE TITLE
Updates to use of Nextclade in ingest workflow

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/pathogen-repo-guide#47]
A list of updates that should be made to the use of nextclade in the ingest workflow that came up with @kimandrews 's work in https://github.com/nextstrain/measles/pull/36 and my own work in https://github.com/nextstrain/avian-flu/issues/44. 

### TODOs

1. Update to Nextclade v3. This guide was written before the official release but Nextclade v3 been out for ~6 months now and all new Nextclade datasets are expected to be v3. 
    - [x] update `nextclade2` to `nextclade3`
    - [x] update `results/translations/{gene}.fasta` to `results/translations/{cds}.fasta`
2. Update the [nextclade_field_map.tsv](https://github.com/nextstrain/pathogen-repo-guide/blob/main/ingest/defaults/nextclade_field_map.tsv).
    - [x] remove `lineage` - this is mpox specific
    - [ ] consider adding more columns (a la [measles](https://github.com/nextstrain/measles/blob/main/ingest/defaults/nextclade_field_map.tsv))
3. ~Wrap [uses of csvtk](https://github.com/nextstrain/pathogen-repo-guide/blob/e3bfb52c8155058a3d48592f4268a7382bf3e12a/ingest/rules/nextclade.smk#L78-L85) with `csvtk fix-quotes` similar to https://github.com/nextstrain/pathogen-repo-guide/commit/c0b9e509c544c8c87763c5beeb3039f48d82975b~ Ran into errors with csvtk fix-quotes, see https://github.com/nextstrain/pathogen-repo-guide/issues/55
